[package]
name = "isq"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
fraction = "0.6.3"
alga = "0.9.3"
alga_derive = "0.9.2"
num-traits = "0.2.11"
GSL = "*"